services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector
    environment:
      - 'POSTGRES_DB=vectordb'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./pgvector_data:/var/lib/postgres/data
volumes:
  pgvector_data: